In [1]:
import numpy as np

In [11]:
array = np.arange(0,400,5)
array

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220, 225, 230, 235, 240, 245, 250, 255,
       260, 265, 270, 275, 280, 285, 290, 295, 300, 305, 310, 315, 320,
       325, 330, 335, 340, 345, 350, 355, 360, 365, 370, 375, 380, 385,
       390, 395])

In [17]:
array = array.reshape((10,8))

In [23]:
array.shape

(10, 8)

In [25]:
array[3]

array([120, 125, 130, 135, 140, 145, 150, 155])

In [27]:
array.dtype

dtype('int32')

In [33]:
array.ndim

2

### Performance Measurement

In [38]:
c = range(1000)
%timeit [i**3 for i in c]

121 μs ± 19.5 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [40]:
c_numpy = np.arange(1000)
%timeit c_numpy**3

4.99 μs ± 695 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


- Another Function

In [43]:
l1 = range(1000)
l2 = [i**2 for i in l1]


In [45]:
%timeit list(map(lambda x,y:x*y, l1,l2))

134 μs ± 20.2 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [47]:
arr1 = np.array(l1)
arr2 = np.array(l2)

In [49]:
%timeit arr1*arr2

1.71 μs ± 223 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [57]:
np.arange(24).reshape(6,1,4)

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]],

       [[12, 13, 14, 15]],

       [[16, 17, 18, 19]],

       [[20, 21, 22, 23]]])

In [65]:
a = np.arange(1,17).reshape((4,4))
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [71]:
a[:1,2:]

array([[3, 4]])

In [73]:
a*2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [75]:
a>5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [77]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [79]:
a[(a>2)&(a<10)]

array([3, 4, 5, 6, 7, 8, 9])

In [81]:
a.T

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [83]:
a * a.T

array([[  1,  10,  27,  52],
       [ 10,  36,  70, 112],
       [ 27,  70, 121, 180],
       [ 52, 112, 180, 256]])

In [87]:
np.vstack((a,a.T))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [89]:
np.hstack((a,a.T))

array([[ 1,  2,  3,  4,  1,  5,  9, 13],
       [ 5,  6,  7,  8,  2,  6, 10, 14],
       [ 9, 10, 11, 12,  3,  7, 11, 15],
       [13, 14, 15, 16,  4,  8, 12, 16]])

In [91]:
a.sum()

136

In [95]:
np.median(a)

8.5

In [97]:
np.linalg.inv(a)

array([[ 1.50119988e+15, -3.75299969e+14, -3.75299969e+15,
         2.62709978e+15],
       [-1.95155984e+16,  1.95155984e+16,  1.95155984e+16,
        -1.95155984e+16],
       [ 3.45275971e+16, -3.79052969e+16, -2.77721977e+16,
         3.11498974e+16],
       [-1.65131986e+16,  1.87649984e+16,  1.20095990e+16,
        -1.42613988e+16]])

In [101]:
np.linalg.eig(a)

EigResult(eigenvalues=array([ 3.62093727e+01, -2.20937271e+00, -2.57831463e-15,  5.57979826e-17]), eigenvectors=array([[-0.15115432,  0.72704996,  0.51747505, -0.06588506],
       [-0.34923733,  0.28320876, -0.82375673, -0.31743721],
       [-0.54732033, -0.16063243,  0.09508831,  0.83252961],
       [-0.74540333, -0.60447363,  0.21119337, -0.44920733]]))

In [105]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [103]:
a.sum(axis=0)

array([28, 32, 36, 40])

In [107]:
a.max()

16

In [113]:
a.argmax(axis=0)

array([3, 3, 3, 3], dtype=int64)

In [119]:
a[:,:,np.newaxis]

array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12]],

       [[13],
        [14],
        [15],
        [16]]])

In [127]:
np.sort(a)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [131]:
a.argsort()

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int64)

In [145]:
b = np.random.randint(1,100,16).reshape((4,4))

In [147]:
b

array([[63, 82, 98, 90],
       [89, 57, 72, 31],
       [67, 85, 43,  2],
       [ 2, 79, 56, 13]])

In [149]:
np.sort(b)

array([[63, 82, 90, 98],
       [31, 57, 72, 89],
       [ 2, 43, 67, 85],
       [ 2, 13, 56, 79]])

In [151]:
np.argsort(b)

array([[0, 1, 3, 2],
       [3, 1, 2, 0],
       [3, 2, 0, 1],
       [0, 3, 2, 1]], dtype=int64)